### ISSUE TITLE
API key needed

### ISSUE THREAD

**Issue by miostreams** [szantaii/bash-weather#3]
Within the last few days, the app stopped fetching the weather data. The program runs without error, but just doesn't display the actual weather.
Reviewing the get-weather-data.sh file, I added an API key to the end of each URI listed (two occurrences each of current_weather_data and weather_forecast_data), in the form of APPID=<my key>. For example, this:
current_weather_data=$(curl -s "http://api.openweathermap.org/\
data/2.5/weather?lat=${latitude}&lon=${longitude}&mode=xml&\
units=${unit_type}&APPID=<my key>")

Of course, this means that you have to sign up for an API key with openweathermap.org, so you have an API key to enter here.  I will probably end up pulling the key from a file long term, but I thought I would mention it here to see if you had a better idea on handling the issue.

**Comment by szantaii** [comment]
Thank you for reporting this problem.

I have added the [OpenWeatherMap API key](http://openweathermap.org/appid) support. Now each user has to provide their own OpenWeatherMap API key either in the `openweathermap.key` file or in the command-line by using the `-k` option.

Please check this solution, I am awaiting for your reply.

(I am sorry I could only answer this slow, but I was moving flats in the last weeks.)

**Comment by szantaii** [comment]
I am closing this issue as it is now fixed.

**Comment by miostreams** [comment]
My sincere apologies for not getting back to this sooner.  It works like a charm!
